MagicVillaWeb/Models/ViewModelDTO/VillaNumberViewModel.cs
using MagicVillaWeb.Model.DTO;

namespace MagicVillaWeb.Models.ViewModelDTO
{
    public class VillaNumberViewModel
    {
        public VillaNumberDTOUpdate VillaNumberDTOUpdate { get; set; }
        public List<VillaDTO> Villas { get; set; }
    }
}

MagicVillaWeb/Controllers/VillaController.cs
using AutoMapper;
using MagicVillaWeb.Model;
using MagicVillaWeb.Model.DTO;
using MagicVillaWeb.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MagicVillaWeb.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _villaService;
        private readonly IMapper _mapper;

        public VillaController(IVillaService villaService, IMapper mapper)
        {
            _villaService = villaService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexVilla()
        {
            List<VillaDTO> list = new();
            var response = await _villaService.GetAllAsync<ApiResponse>();
            if (response != null && response.isSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }
            return View(list);
        }
        [HttpGet]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVilla(VillaDTOCreate model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.CreateAsync<ApiResponse>(model);
                if (response != null && response.isSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateVilla(int villaId)
        {
            var response = await _villaService.GetAsync<ApiResponse>(villaId);
            if (response != null && response.isSuccess)
            {
                VillaDTO villa = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(_mapper.Map<VillaDTOUpdate>(villa));
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVilla(VillaDTOUpdate model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaService.UpdateAsync<ApiResponse>(model);
                if (response != null && response.isSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            return View(model);
        }
        public async Task<IActionResult> DeleteVilla(int villaId)
        {
            var response = await _villaService.GetAsync<ApiResponse>(villaId);
            if (response != null && response.isSuccess)
            {
                VillaDTO villa = JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(response.Result));
                return View(villa);
            }
            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> DeleteVilla(VillaDTO model)
        {
            var response = await _villaService.DeleteAsync<ApiResponse>(model.Id);
            if (response != null && response.isSuccess)
            {
                return RedirectToAction(nameof(IndexVilla));
            }
            return NotFound();
        }
    }
}

MagicVillaWeb/Controllers/VillaNumberController.cs
using AutoMapper;
using MagicVillaWeb.Model;
using MagicVillaWeb.Model.DTO;
using MagicVillaWeb.Models;
using MagicVillaWeb.Models.ViewModelDTO;
using MagicVillaWeb.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MagicVillaWeb.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _serviceVillaNumber;
        private readonly IMapper _mapper;
        private readonly IVillaService _serviceVilla;

        public VillaNumberController(IVillaNumberService serviceVillaNumber, IVillaService serviceVilla, IMapper mapper)
        {
            _serviceVillaNumber = serviceVillaNumber;
            _serviceVilla = serviceVilla;
            _mapper = mapper;
        }
        [HttpGet]
        public async Task<IActionResult> IndexVillaNumber()
        {
            List<VillaNumberDTO> list = new();
            var resonse = await _serviceVillaNumber.GetAllAsync<ApiResponse>();
            if (resonse.isSuccess)
            {
                list = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(Convert.ToString(resonse.Result));
            }
            return View(list);
        }      
        [HttpGet]
        public async Task<IActionResult> CreateVillaNumber()
        {
            List<VillaDTO> villas = new();
            var response = await _serviceVilla.GetAllAsync<ApiResponse>();

            if (response.isSuccess)
            {
                villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response.Result));
            }
            return View(villas);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVillaNumber(VillaNumberDTOCreate numberDTOCreate)
        {
            var response = await _serviceVillaNumber.CreateAsync<ApiResponse>(numberDTOCreate);

            if (response != null && response.isSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
            return View(numberDTOCreate);
        }
        [HttpGet]
        public async Task<IActionResult> UpdateVillaNumber(int id)
        {
            List<VillaDTO> villas = new();
            VillaNumberDTOUpdate dTOUpdate = new();
            VillaNumberViewModel updateVilla = new();

            updateVilla.Villas = villas;
            updateVilla.VillaNumberDTOUpdate = dTOUpdate;

            var response_list = await _serviceVilla.GetAllAsync<ApiResponse>();
            var response_obj = await _serviceVillaNumber.GetAsync<ApiResponse>(id);

            if (response_list.isSuccess && response_obj.isSuccess)
            {
                updateVilla.Villas = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(response_list.Result));
                updateVilla.VillaNumberDTOUpdate = JsonConvert.DeserializeObject<VillaNumberDTOUpdate>(Convert.ToString(response_obj.Result));

                return View(updateVilla);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateVillaNumber(VillaNumberViewModel villaNumberViewModel)
        {
            var response = await _serviceVillaNumber.UpdateAsync<ApiResponse>(villaNumberViewModel.VillaNumberDTOUpdate);

            if (response.isSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
            return View(villaNumberViewModel);
        }
        [HttpGet]
        public async Task<IActionResult> DeleteVillaNumber(int id)
        {
            VillaNumberDTO villa = new();
            var response = await _serviceVillaNumber.GetAsync<ApiResponse>(id);
            if (response.isSuccess)
            {
                villa = JsonConvert.DeserializeObject<VillaNumberDTO>(Convert.ToString(response.Result));
            }
            return View(villa);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteVillaNumber(VillaNumberDTO villaNumber)
        {
            VillaNumberDTO villa = new();
            var response = await _serviceVillaNumber.DeleteAsync<ApiResponse>(villaNumber.VillaNo);
            if (response.isSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
            return NotFound();
        }

    }
}

MagicVillaWeb/Views/VillaNumber/CreateVillaNumber.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Create Villa</h2>

MagicVillaWeb/Views/VillaNumber/DeleteVillaNumber.cshtml
@model MagicVillaWeb.Model.DTO.VillaNumberDTO
<form asp-action="DeleteVilla">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete Villa </h1>
        <hr />
        <input asp-for="VillaNo" style="visibility:hidden" />
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Villa.Name" class="control-label pt-2" style="font-size:20px"></label>
            </div>
           
            <div class="col-2">
                <label asp-for="SpecialDetails" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            
            <div class="col-5 offset-2">
                <a asp-action="IndexVilla" asp-controller="Villa" class="btn-primary btn form-control">Back to List</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-warning form-control" />
            </div>
        </div>
    </div>
</form>

MagicVillaWeb/Views/VillaNumber/IndexVillaNumber.cshtml
@model IEnumerable<MagicVillaWeb.Model.DTO.VillaNumberDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Villa List</h1>
        </div>
        <div class="col text-end pt=1">
            <a asp-controller="VillaNumber" asp-action="CreateVillaNuber" class="btn btn-outline-primary pt-1">
                <i class="bi bi-file-plus"></i> Create New Villa Number
            </a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>

                <th>
                    Occupancy
                </th>
               
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Villa.Name
                    </td>
                    <td>
                        @item.SpecialDetails
                    </td>
                    
                    <td>
                        <a asp-controller="Villa" asp-action="UpdateVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-success pt-1">
                            <i class="bi bi-pencil-square"></i>Update
                        </a> <a asp-controller="Villa" asp-action="DeleteVillaNumber" asp-route-villaNo="@item.VillaNo" class="btn btn-danger pt-1">
                            <i class="bi bi-trash"></i> Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

MagicVillaWeb/Views/VillaNumber/UpdateVillaNumber.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Update Villa</h2>